name: DevTools
main: DevTools\DevTools
load: STARTUP
author: lakwsh
description: Helps develop and distribute PocketMine-MP plugins
api:
 - 3.0.0
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10

commands:
 makeserver:
  description: Creates a PocketMine-MP Phar
  usage: "/makeserver"
  permission: devtools.op
 makeplugin:
  description: Creates a Phar plugin from one in source code form
  usage: "/makeplugin <pluginName>"
  permission: devtools.op
 ms:
  description: Creates a PocketMine-MP Phar
  usage: "/ms"
  permission: devtools.op
 mp:
  description: Creates a Phar plugin from one in source code form
  usage: "/mp <pluginName>"
  permission: devtools.op

permissions:
 devtools:
  default: false
  description: false
  children:
   devtools.op:
    default: op
    description: false
   devtools.all:
    default: true
    description: false
